### ISSUE TITLE
Jump To Page Doesn't Show Initial Value

### ISSUE THREAD

**Issue by Miserlou** [AlexsLemonade/refinebio-frontend#440]
![screen shot 2018-11-26 at 8 04 06 pm](https://user-images.githubusercontent.com/139987/49051580-7b504480-f1b6-11e8-8595-b51fcf277f71.png)

**Comment by dvenprasad** [comment]
What is the use case for showing an initial value?

**Comment by arielsvn** [comment]
> Because what do up-arrow-down-arrow mean if there is no value displayed.

This is something that we can address with https://github.com/AlexsLemonade/refinebio-frontend/issues/441, and ensure the arrows are not displayed initially

**Comment by arielsvn** [comment]
@Miserlou can we close this? We deployed several cosmetic improvements for jump to page.

**Comment by Miserlou** [comment]
I still do not see an initial value.
![screen shot 2019-02-14 at 2 08 27 pm](https://user-images.githubusercontent.com/139987/52811014-0cbaae80-3062-11e9-950c-f5343fcc6279.png)

**Comment by arielsvn** [comment]
I asked because we addressed what you mentioned in https://github.com/AlexsLemonade/refinebio-frontend/issues/440#issuecomment-443875900, by removing the up/down arrows and improving the overall styles. 

Why do you think it's better to show the initial value?

**Comment by Miserlou** [comment]
The solution to the arrows would be to add the value, not remove the arrows.
